{% set version = '2.1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-testthat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/testthat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/testthat/testthat_{{ version }}.tar.gz
  sha256: 776ebc8ba07ba41ac4f402e4cf1a525a66e9a50763931515b8fe9c4c21c84f0e

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-r6 >=2.2.0
    - r-cli
    - r-crayon >=1.3.4
    - r-digest
    - r-magrittr
    - r-praise
    - r-rlang >=0.3.0
    - r-withr >=2.0.0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-r6 >=2.2.0
    - r-cli
    - r-crayon >=1.3.4
    - r-digest
    - r-magrittr
    - r-praise
    - r-rlang >=0.3.0
    - r-withr >=2.0.0

test:
  commands:
    - $R -e "library('testthat')"           # [not win]
    - "\"%R%\" -e \"library('testthat')\""  # [win]

about:
  home: http://testthat.r-lib.org, https://github.com/r-lib/testthat
  license: MIT
  summary: Software testing is important, but, in part because it is  frustrating and boring,
    many of us avoid it. 'testthat' is a testing framework  for R that is easy learn
    and use, and integrates with your existing 'workflow'.
  license_family: MIT
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: testthat
# Title: Unit Testing for R
# Version: 2.1.1
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", c("aut", "cre")), person("RStudio", role = c("cph", "fnd")), person("R Core team", role = "ctb", comment = "Implementation of utils::recover()") )
# Description: Software testing is important, but, in part because it is  frustrating and boring, many of us avoid it. 'testthat' is a testing framework  for R that is easy learn and use, and integrates with your existing 'workflow'.
# License: MIT + file LICENSE
# URL: http://testthat.r-lib.org, https://github.com/r-lib/testthat
# BugReports: https://github.com/r-lib/testthat/issues
# Depends: R (>= 3.1)
# Imports: cli, crayon (>= 1.3.4), digest, magrittr, methods, praise, R6 (>= 2.2.0), rlang (>= 0.3.0), withr (>= 2.0.0)
# Suggests: covr, curl (>= 0.9.5), devtools, knitr, rmarkdown, usethis, vctrs (>= 0.1.0), xml2
# VignetteBuilder: knitr
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# Collate: 'auto-test.R' 'capture-condition.R' 'capture-output.R' 'colour-text.R' 'compare.R' 'compare-character.R' 'compare-numeric.R' 'compare-time.R' 'context.R' 'describe.R' 'evaluate-promise.R' 'example.R' 'expect-comparison.R' 'expect-equality.R' 'expect-inheritance.R' 'expect-invisible.R' 'expect-known.R' 'expect-length.R' 'expect-logical.R' 'expect-named.R' 'expect-null.R' 'expect-output.R' 'reporter.R' 'expect-self-test.R' 'expect-setequal.R' 'expect-that.R' 'expect-vector.R' 'expectation.R' 'expectations-matches.R' 'make-expectation.R' 'mock.R' 'old-school.R' 'praise.R' 'quasi-label.R' 'recover.R' 'reporter-check.R' 'reporter-debug.R' 'reporter-fail.R' 'reporter-junit.R' 'reporter-list.R' 'reporter-location.R' 'reporter-minimal.R' 'reporter-multi.R' 'stack.R' 'reporter-progress.R' 'reporter-rstudio.R' 'reporter-silent.R' 'reporter-stop.R' 'reporter-summary.R' 'reporter-tap.R' 'reporter-teamcity.R' 'reporter-zzz.R' 'skip.R' 'source.R' 'teardown.R' 'test-compiled-code.R' 'test-directory.R' 'test-example.R' 'test-files.R' 'test-path.R' 'test-that.R' 'traceback.R' 'try-again.R' 'utils-io.R' 'utils.R' 'watcher.R'
# NeedsCompilation: yes
# Packaged: 2019-04-23 15:10:28 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph, fnd], R Core team [ctb] (Implementation of utils::recover())
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-04-23 22:40:03 UTC
