{% set version = "3.3.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-testthat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/testthat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/testthat/testthat_{{ version }}.tar.gz
  sha256: cb6242958de41afe82b6aad566b7628f8864f61696780b7eacc709e946685620

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-brio >=1.1.3               # [build_platform != target_platform]
    - r-callr >=3.7.3              # [build_platform != target_platform]
    - r-cli >=3.6.1                # [build_platform != target_platform]
    - r-desc >=1.4.2               # [build_platform != target_platform]
    - r-digest >=0.6.33            # [build_platform != target_platform]
    - r-evaluate >=1.0.1           # [build_platform != target_platform]
    - r-jsonlite >=1.8.7           # [build_platform != target_platform]
    - r-lifecycle >=1.0.3          # [build_platform != target_platform]
    - r-magrittr >=2.0.3           # [build_platform != target_platform]
    - r-pkgload >=1.3.2.1          # [build_platform != target_platform]
    - r-praise >=1.0.0             # [build_platform != target_platform]
    - r-processx >=3.8.2           # [build_platform != target_platform]
    - r-ps >=1.7.5                 # [build_platform != target_platform]
    - r-r6 >=2.5.1                 # [build_platform != target_platform]
    - r-rlang >=1.1.1              # [build_platform != target_platform]
    - r-waldo >=0.6.0              # [build_platform != target_platform]
    - r-withr >=3.0.2              # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-brio >=1.1.3
    - r-callr >=3.7.3
    - r-cli >=3.6.1
    - r-desc >=1.4.2
    - r-digest >=0.6.33
    - r-evaluate >=1.0.1
    - r-jsonlite >=1.8.7
    - r-lifecycle >=1.0.3
    - r-magrittr >=2.0.3
    - r-pkgload >=1.3.2.1
    - r-praise >=1.0.0
    - r-processx >=3.8.2
    - r-ps >=1.7.5
    - r-r6 >=2.5.1
    - r-rlang >=1.1.1
    - r-waldo >=0.6.0
    - r-withr >=3.0.2
  run:
    - r-base
    - r-brio >=1.1.3
    - r-callr >=3.7.3
    - r-cli >=3.6.1
    - r-desc >=1.4.2
    - r-digest >=0.6.33
    - r-evaluate >=1.0.1
    - r-jsonlite >=1.8.7
    - r-lifecycle >=1.0.3
    - r-magrittr >=2.0.3
    - r-pkgload >=1.3.2.1
    - r-praise >=1.0.0
    - r-processx >=3.8.2
    - r-ps >=1.7.5
    - r-r6 >=2.5.1
    - r-rlang >=1.1.1
    - r-waldo >=0.6.0
    - r-withr >=3.0.2

test:
  commands:
    - $R -e "library('testthat')"           # [not win]
    - "\"%R%\" -e \"library('testthat')\""  # [win]

about:
  home: http://testthat.r-lib.org
  dev_url: https://github.com/r-lib/testthat
  license: MIT
  summary: Software testing is important, but, in part because it is frustrating and boring, many of us avoid it. 'testthat' is a testing framework for R that is easy to learn and use, and integrates with your existing 'workflow'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
