# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxtarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxtarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "VhyJ3SB7SCKzmP0KDKCGzCLmb0RGhhSU9gG4THFLxu4tFXpO6EPlTtpbyRNcGUFZaAHHdaoUmbJV2Ph0pfy9TBby9Tg0H2G5xwRVZMV0Ni1XroKBwy9JdnqnxLTXN0E/OGUf5wrmlUDa7NPDtMa3sxbeJ6BuVW/WPvOwvaaoRam4MTkUrSOh3OcKVWTt3K74VlUTAKU0gQ1bAcsCoT+ySMqkDzlcnJxviE6fhLNoKRl565BA8f8/UuoTb8Zz2kvvnPxNpHVUDDXj8ZRoGcpshkXif9xKBkDjABy1V7e+CefI83FuGArBThC+OB5qEMUkbXko+dKu3DlCSAejX/YrhazjF7G+C9wzGWHrCZgHl0G18iaa00tb24XYIk7fQgcwcgOCmCEme6EZgitsS8q2mtkWoJVmR0EI6K8P+IuJr9tFMYQ+yHUrXeYC66dfKebzUqx8y19JC8SA4M+T0JG+9gWhgcVdpnAPUJq5TdG2tqG8tuDKDj5UgO1DL9FLezKDE273A1588GOxcUVelVPRydzfy9ymkB89WlGcxT+weSPYfIvaI58I3UYUIPbrG0u3TQNU0ResZ2eiw+8q1eD1X+FHDdRqv058hvoixSGVyMmCyCadpPJ5BlxdSa4ErtPml9ZBcXUqPiJz4Dih7YHn+GnRsQwc3xWLo7Ci4Lcpnx8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
