travis:
  secure:
    BINSTAR_TOKEN: VhyJ3SB7SCKzmP0KDKCGzCLmb0RGhhSU9gG4THFLxu4tFXpO6EPlTtpbyRNcGUFZaAHHdaoUmbJV2Ph0pfy9TBby9Tg0H2G5xwRVZMV0Ni1XroKBwy9JdnqnxLTXN0E/OGUf5wrmlUDa7NPDtMa3sxbeJ6BuVW/WPvOwvaaoRam4MTkUrSOh3OcKVWTt3K74VlUTAKU0gQ1bAcsCoT+ySMqkDzlcnJxviE6fhLNoKRl565BA8f8/UuoTb8Zz2kvvnPxNpHVUDDXj8ZRoGcpshkXif9xKBkDjABy1V7e+CefI83FuGArBThC+OB5qEMUkbXko+dKu3DlCSAejX/YrhazjF7G+C9wzGWHrCZgHl0G18iaa00tb24XYIk7fQgcwcgOCmCEme6EZgitsS8q2mtkWoJVmR0EI6K8P+IuJr9tFMYQ+yHUrXeYC66dfKebzUqx8y19JC8SA4M+T0JG+9gWhgcVdpnAPUJq5TdG2tqG8tuDKDj5UgO1DL9FLezKDE273A1588GOxcUVelVPRydzfy9ymkB89WlGcxT+weSPYfIvaI58I3UYUIPbrG0u3TQNU0ResZ2eiw+8q1eD1X+FHDdRqv058hvoixSGVyMmCyCadpPJ5BlxdSa4ErtPml9ZBcXUqPiJz4Dih7YHn+GnRsQwc3xWLo7Ci4Lcpnx8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
